import jsPDF from 'jspdf';
import { RoadmapData } from './types';

interface ExportSection {
  id: string;
  name: string;
  milestone: string;
  topics: Array<{
    id: string;
    name: string;
    estimatedHours: number;
    difficulty: string;
    subtopics?: string[];
  }>;
}

interface ExportMeta {
  userName?: string;
  completedTopicIds?: string[];
  sections?: ExportSection[];
}

function drawFooter(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageNo = doc.getNumberOfPages();

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(`Generated by LearnFlow · ${new Date().toLocaleDateString()}`, 14, pageHeight - 8);
  doc.text(`Page ${pageNo}`, pageWidth - 24, pageHeight - 8);
}

export async function exportToPDF(roadmapData: RoadmapData, meta: ExportMeta = {}): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const completedSet = new Set(meta.completedTopicIds ?? []);

  const sections: ExportSection[] =
    meta.sections && meta.sections.length > 0
      ? meta.sections
      : roadmapData.phases.map((phase) => ({
          id: phase.id,
          name: phase.name,
          milestone: phase.milestone,
          topics: phase.topics.map((topic) => ({
            id: topic.id,
            name: topic.name,
            estimatedHours: topic.estimatedHours,
            difficulty: topic.difficulty,
            subtopics: [],
          })),
        }));

  const allTopics = sections.flatMap((section) => section.topics);
  const totalTopics = allTopics.length;
  const completedTopics = allTopics.filter((topic) => completedSet.has(topic.id)).length;
  const remainingTopics = Math.max(0, totalTopics - completedTopics);
  const progressPercent = totalTopics > 0 ? Math.round((completedTopics / totalTopics) * 100) : 0;

  const totalHours = allTopics.reduce((sum, topic) => sum + topic.estimatedHours, 0);
  const completedHours = allTopics
    .filter((topic) => completedSet.has(topic.id))
    .reduce((sum, topic) => sum + topic.estimatedHours, 0);
  const remainingHours = Math.max(0, totalHours - completedHours);

  const learnerName = meta.userName?.trim() || 'Learner';
  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(17, 24, 39);
  doc.text('LearnFlow Weekly Progress Report', 14, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(55, 65, 81);
  doc.text(`User: ${learnerName}`, 14, 26);
  doc.text(`Track: ${roadmapData.domain} - ${roadmapData.subTrack}`, 14, 32);

  // Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39);
  doc.text('Overall Progress', 14, 42);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  doc.text(`Weeks: ${sections.length}`, 14, 49);
  doc.text(`Topics done: ${completedTopics}`, 56, 49);
  doc.text(`Topics left: ${remainingTopics}`, 106, 49);
  doc.text(`Progress: ${progressPercent}%`, 154, 49);
  doc.text(`Hours done: ${completedHours}h`, 198, 49);
  doc.text(`Hours left: ${remainingHours}h`, 244, 49);

  // Week-wise status table
  let y = 60;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text('Week-wise Status', 14, y);

  y += 8;
  doc.setDrawColor(210, 214, 224);
  doc.setFillColor(246, 247, 252);
  doc.rect(14, y - 5, 182, 7, 'FD');

  doc.setFontSize(9);
  doc.text('Week', 16, y);
  doc.text('Planned', 50, y);
  doc.text('Done', 75, y);
  doc.text('Left', 92, y);
  doc.text('Hours Planned', 108, y);
  doc.text('Hours Done', 138, y);
  doc.text('Hours Left', 164, y);

  y += 6;
  doc.setFont('helvetica', 'normal');

  sections.forEach((section, index) => {
    const done = section.topics.filter((topic) => completedSet.has(topic.id)).length;
    const left = section.topics.length - done;
    const plannedHours = section.topics.reduce((sum, topic) => sum + topic.estimatedHours, 0);
    const doneHours = section.topics
      .filter((topic) => completedSet.has(topic.id))
      .reduce((sum, topic) => sum + topic.estimatedHours, 0);
    const leftHours = plannedHours - doneHours;

    if (y > 250) {
      drawFooter(doc);
      doc.addPage();
      y = 20;
    }

    doc.setDrawColor(234, 236, 245);
    doc.line(14, y + 1, 196, y + 1);
    doc.text(`${index + 1}. ${section.name}`, 16, y);
    doc.text(`${section.topics.length}`, 54, y);
    doc.text(`${done}`, 77, y);
    doc.text(`${left}`, 94, y);
    doc.text(`${plannedHours}h`, 113, y);
    doc.text(`${doneHours}h`, 141, y);
    doc.text(`${leftHours}h`, 167, y);
    y += 7;
  });

  // Full learning plan by week/day
  y += 6;
  if (y > 220) {
    drawFooter(doc);
    doc.addPage();
    y = 20;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text('What To Learn (All Topics by Week)', 14, y);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(55, 65, 81);

  sections.forEach((section, index) => {
    if (y > 258) {
      drawFooter(doc);
      doc.addPage();
      y = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}. ${section.name}`, 16, y);
    y += 5;
    doc.setFont('helvetica', 'normal');

    section.topics.forEach((topic) => {
      if (y > 258) {
        drawFooter(doc);
        doc.addPage();
        y = 20;
      }
      const status = completedSet.has(topic.id) ? '[Done]' : '[Left]';
      doc.text(`- ${status} ${topic.name} (${topic.estimatedHours}h)`, 20, y);
      y += 4.6;

      const topicSubtopics = topic.subtopics ?? [];
      topicSubtopics.forEach((subtopic) => {
        if (y > 258) {
          drawFooter(doc);
          doc.addPage();
          y = 20;
        }
        doc.text(`    - ${subtopic}`, 24, y);
        y += 4.2;
      });
    });

    y += 2;
  });

  // Required work left by week
  y += 6;
  if (y > 220) {
    drawFooter(doc);
    doc.addPage();
    y = 20;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text('What Is Left To Do (by Week)', 14, y);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(55, 65, 81);

  sections.forEach((section, index) => {
    const pending = section.topics.filter((topic) => !completedSet.has(topic.id));

    if (y > 258) {
      drawFooter(doc);
      doc.addPage();
      y = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}. ${section.name}`, 16, y);
    y += 5;
    doc.setFont('helvetica', 'normal');

    if (pending.length === 0) {
      doc.text('- Completed', 20, y);
      y += 5;
      return;
    }

    pending.forEach((topic) => {
      if (y > 258) {
        drawFooter(doc);
        doc.addPage();
        y = 20;
      }
      doc.text(`- ${topic.name} (${topic.estimatedHours}h)`, 20, y);
      y += 4.6;
    });

    y += 2;
  });

  drawFooter(doc);

  doc.save(`LearnFlow_${roadmapData.subTrack.replace(/\s/g, '_')}_Roadmap_Report.pdf`);
}
